students/urls.py
from django.urls import path

from . import views

app_name = 'students'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('edit/<int:student_id>/', views.edit, name='edit'),
    path('delete/<int:student_id>/', views.delete, name='delete'),
    path('insert/', views.insert, name='insert'),
    path('update/<int:student_id>/', views.update, name='update'),
]

students_crud/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
]

students/models.py
from django.db import models


class Student(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()

students/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from .models import Student


def index(request):
    students = Student.objects.all()
    context = {'students': students}
    return render(request, 'students/index.html', context)


def add(request):
    return render(request, 'students/add.html')


def insert(request):
    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')
    age = request.POST.get('age')
    student = Student(first_name=first_name, last_name=last_name, age=age)
    student.save()
    return HttpResponseRedirect('/students/')


def edit(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    context = {'student': student}
    return render(request, 'students/edit.html', context)


def update(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    student.first_name = request.POST.get('first_name')
    student.last_name = request.POST.get('last_name')
    student.age = request.POST.get('age')
    student.save()
    return HttpResponseRedirect('/students/')


def delete(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    student.delete()
    return HttpResponseRedirect('/students/')

students/templates/students/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Student</title>
</head>
<body>
    <form method="POST" action="{% url 'students:insert' %}">
        {% csrf_token %}
        <div>
            <label>First Name: </label>
            <input type="text" name="first_name">
        </div><br>
        <div>
            <label>Last Name: </label>
            <input type="text" name="last_name">
        </div><br>
        <div>
            <label>Age: </label>
            <input type="number" name="age">
        </div>
        <input type="submit" name="submit" value="submit">
    </form>
</body>
</html>

students/templates/students/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Student</title>
</head>
<body>
    <form method="POST" action="{% url 'students:update' student.id %}">
        {% csrf_token %}
        <div>
            <label>First Name: </label>
            <input type="text" name="first_name" value="{{student.first_name}}">
        </div><br>
        <div>
            <label>Last Name: </label>
            <input type="text" name="last_name" value="{{student.last_name}}">
        </div><br>
        <div>
            <label>Age: </label>
            <input type="number" name="age" value="{{student.age}}">
        </div>
        <input type="submit" name="submit" value="submit">
    </form>
</body>
</html>

students/templates/students/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Our Students</title>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
            text-align: center;
        }

    </style>
</head>
<body>
    <h1>List of Students</h1><hr>
    <a href="{% url 'students:add' %}" style="float:right;">Add New Student</a>
    <div style="clear:both;"></div><br>
    <table style="width: 100%;">
        <thead>
            <td>First Name</td>
            <td>Last Name</td>
            <td>Age</td>
            <td colspan="2">Actions</td>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <td>{{student.first_name}}</td>
                <td>{{student.last_name}}</td>
                <td>{{student.age}}</td>
                <td><a href="{% url 'students:edit' student.id %}">edit</a></td>
                <td><a href="{% url 'students:delete' student.id %}">delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>